
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace Model
{

    using System;

    public partial class Agents
    {

        public string Id { get; set; }

        public string Name { get; set; }

        public string Province { get; set; }

        public string City { get; set; }

        public string Village { get; set; }

        public Nullable<System.DateTime> Birthday { get; set; }

        public string CareerStatus { get; set; }

        public System.DateTime JoinDate { get; set; }

        public string Rank { get; set; }

        public string RefereeId { get; set; }

        public string RefereeName { get; set; }

        public string AgencyId { get; set; }

        public string AgencyName { get; set; }

        public string AccountBank { get; set; }

        public string AccountBankBranch { get; set; }

        public string Account { get; set; }

        public string Address { get; set; }

        public string ZipCode { get; set; }

        public string Phone { get; set; }

        public Nullable<System.DateTime> CreateTime { get; set; }

        public string CreatePerson { get; set; }

        public Nullable<System.DateTime> UpdateTime { get; set; }

        public string UpdatePerson { get; set; }

        public int State { get; set; }

    }

}
